### ISSUE TITLE
Does not have all the issues with easyfix tag

### ISSUE THREAD

**Issue by trishnaguha** [fedora-infra/fedora-gather-easyfix#7]
https://fedoraproject.org/easyfix/ is not fetching all the issues with easyfix tag. The bugzilla link also doesn't seem to work and the Project list is not there.

**Comment by abhishekarora12** [comment]
@pypingou @ralphbean I tried recreating the error, and found that there is a dangling <title> tag in line 135 in the html file. "Put the update builds in the <title> <br />"
The page works fine when we remove this <title> tag.

**Comment by abhishekarora12** [comment]
I could narrow down the issue to https://github.com/fedora-infra/fedora-gather-easyfix/blob/master/template.html#L133.
The template engine parses html characters `<, > and &` as it is and they are breaking the page. If a ticket has a title with any of these characters, it will break the page.
So we need to replace them by `&lt;, &gt; and &amp;`

The title which was breaking it: https://github.com/fedora-infra/bodhi/issues/649
There is `<title>` in this ticket's title.

**Comment by ralphbean** [comment]
Nice find!  For a fix, take a look at the jinja template docs about how to escape characters like that:  http://jinja.pocoo.org/docs/dev/templates/

**Comment by pypingou** [comment]
Merged :)
